
build:
	make -C nldump
	make -C nlsniff
	make -C nlreverse
	make -C nlhex

clean:
	make -C nldump clean
	make -C nlsniff clean
	make -C nlreverse clean
	make -C nlhex clean

install:
	make -C nldump install
	make -C nlsniff install
	make -C nlreverse install
	make -C nlhex install

install_docker:
	make -C nldump install_docker
	make -C nlsniff install_docker
	make -C nlreverse install_docker
	make -C nlhex install_docker

